/**
 * service-worker.js
 * [experimental] Use service workers to replace static resources
 */

const storageName = 'devtools_app';
const preload = [
  "/front_end/Runtime.js",
  "/front_end/devtools_app.js",
  "/front_end/devtools_app.json",
  "/front_end/shell.json",
  "/front_end/extensions/module.json",
  "/front_end/console_counters/module.json",
  "/front_end/bindings/module.json",
  "/front_end/components/module.json",
  "/front_end/common/module.json",
  "/front_end/dom_extension/module.json",
  "/front_end/host/module.json",
  "/front_end/persistence/module.json",
  "/front_end/main/module.json",
  "/front_end/platform/module.json",
  "/front_end/product_registry/module.json",
  "/front_end/protocol/module.json",
  "/front_end/browser_sdk/module.json",
  "/front_end/sdk/module.json",
  "/front_end/text_utils/module.json",
  "/front_end/services/module.json",
  "/front_end/ui/module.json",
  "/front_end/workspace/module.json",
  "/front_end/changes/module.json",
  "/front_end/cm_modes/module.json",
  "/front_end/cm/module.json",
  "/front_end/color_picker/module.json",
  "/front_end/console/module.json",
  "/front_end/diff/module.json",
  "/front_end/data_grid/module.json",
  "/front_end/event_listeners/module.json",
  "/front_end/heap_snapshot_model/module.json",
  "/front_end/formatter/module.json",
  "/front_end/javascript_metadata/module.json",
  "/front_end/inline_editor/module.json",
  "/front_end/perf_ui/module.json",
  "/front_end/object_ui/module.json",
  "/front_end/profiler/module.json",
  "/front_end/quick_open/module.json",
  "/front_end/search/module.json",
  "/front_end/snippets/module.json",
  "/front_end/settings/module.json",
  "/front_end/source_frame/module.json",
  "/front_end/terminal/module.json",
  "/front_end/text_editor/module.json",
  "/front_end/workspace_diff/module.json",
  "/front_end/protocol_monitor/module.json",
  "/front_end/inspector_main/module.json",
  "/front_end/emulation/module.json",
  "/front_end/mobile_throttling/module.json",
  "/front_end/screencast/module.json",
  "/front_end/browser_debugger/module.json",
  "/front_end/cookie_table/module.json",
  "/front_end/elements/module.json",
  "/front_end/devices/module.json",
  "/front_end/layer_viewer/module.json",
  "/front_end/emulated_devices/module.json",
  "/front_end/sources/module.json",
  "/front_end/help/module.json",
  "/front_end/har_importer/module.json",
  "/front_end/network/module.json",
  "/front_end/product_registry_impl/module.json",
  "/front_end/resources/module.json",
  "/front_end/timeline/module.json",
  "/front_end/timeline_model/module.json",
  "/front_end/web_audio/module.json",
  "/front_end/platform/utilities.js",
  "/front_end/text_utils/Text.js",
  "/front_end/text_utils/TextUtils.js",
  "/front_end/text_utils/TextRange.js",
  "/front_end/dom_extension/DOMExtension.js",
  "/front_end/common/Console.js",
  "/front_end/common/Worker.js",
  "/front_end/common/TextDictionary.js",
  "/front_end/common/Object.js",
  "/front_end/common/ContentProvider.js",
  "/front_end/common/Color.js",
  "/front_end/common/Progress.js",
  "/front_end/common/ResourceType.js",
  "/front_end/common/ParsedURL.js",
  "/front_end/common/StaticContentProvider.js",
  "/front_end/common/OutputStream.js",
  "/front_end/common/SegmentedRange.js",
  "/front_end/common/Throttler.js",
  "/front_end/common/Trie.js",
  "/front_end/common/UIString.js",
  "/front_end/common/ModuleExtensionInterfaces.js",
  "/front_end/common/CharacterIdMap.js",
  "/front_end/common/Settings.js",
  "/front_end/host/InspectorFrontendHostAPI.js",
  "/front_end/host/Platform.js",
  "/front_end/host/UserMetrics.js",
  "/front_end/host/ResourceLoader.js",
  "/front_end/host/InspectorFrontendHost.js",
  "/front_end/ui/checkboxTextLabel.css",
  "/front_end/ui/closeButton.css",
  "/front_end/ui/dialog.css",
  "/front_end/ui/confirmDialog.css",
  "/front_end/ui/dropTarget.css",
  "/front_end/ui/filter.css",
  "/front_end/ui/glassPane.css",
  "/front_end/ui/emptyWidget.css",
  "/front_end/ui/infobar.css",
  "/front_end/ui/inlineButton.css",
  "/front_end/ui/inspectorStyle.css",
  "/front_end/ui/inspectorCommon.css",
  "/front_end/ui/inspectorSyntaxHighlightDark.css",
  "/front_end/ui/inspectorSyntaxHighlight.css",
  "/front_end/ui/inspectorViewTabbedPane.css",
  "/front_end/ui/popover.css",
  "/front_end/ui/listWidget.css",
  "/front_end/ui/progressIndicator.css",
  "/front_end/ui/reportView.css",
  "/front_end/ui/rootView.css",
  "/front_end/ui/radioButton.css",
  "/front_end/ui/searchableView.css",
  "/front_end/ui/slider.css",
  "/front_end/ui/remoteDebuggingTerminatedScreen.css",
  "/front_end/ui/softDropDown.css",
  "/front_end/ui/smallBubble.css",
  "/front_end/ui/softDropDownButton.css",
  "/front_end/ui/segmentedButton.css",
  "/front_end/ui/softContextMenu.css",
  "/front_end/ui/splitWidget.css",
  "/front_end/ui/suggestBox.css",
  "/front_end/ui/textButton.css",
  "/front_end/ui/tabbedPane.css",
  "/front_end/ui/toolbar.css",
  "/front_end/ui/targetCrashedScreen.css",
  "/front_end/ui/textPrompt.css",
  "/front_end/ui/tooltip.css",
  "/front_end/ui/viewContainers.css",
  "/front_end/protocol/NodeURL.js",
  "/front_end/ui/treeoutline.css",
  "/front_end/protocol/InspectorBackend.js",
  "/front_end/services/ServiceManager.js",
  "/front_end/workspace/FileManager.js",
  "/front_end/ui/XElement.js",
  "/front_end/workspace/Workspace.js",
  "/front_end/ui/InspectorView.js",
  "/front_end/ui/treeoutline.js",
  "/front_end/workspace/UISourceCode.js",
  "/front_end/ui/ActionRegistry.js",
  "/front_end/InspectorBackendCommands.js",
  "/front_end/ui/ShortcutRegistry.js",
  "/front_end/ui/Context.js",
  "/front_end/ui/Widget.js",
  "/front_end/ui/View.js",
  "/front_end/ui/ContextMenu.js",
  "/front_end/ui/Dialog.js",
  "/front_end/ui/SyntaxHighlighter.js",
  "/front_end/ui/EmptyWidget.js",
  "/front_end/ui/DropTarget.js",
  "/front_end/ui/GlassPane.js",
  "/front_end/ui/FilterSuggestionBuilder.js",
  "/front_end/ui/ForwardedInputEventHandler.js",
  "/front_end/ui/HistoryInput.js",
  "/front_end/ui/Fragment.js",
  "/front_end/ui/FilterBar.js",
  "/front_end/ui/Infobar.js",
  "/front_end/ui/TextEditor.js",
  "/front_end/ui/KeyboardShortcut.js",
  "/front_end/ui/InplaceEditor.js",
  "/front_end/ui/ListModel.js",
  "/front_end/ui/Icon.js",
  "/front_end/ui/Panel.js",
  "/front_end/ui/Popover.js",
  "/front_end/ui/ProgressIndicator.js",
  "/front_end/ui/ResizerWidget.js",
  "/front_end/ui/RemoteDebuggingTerminatedScreen.js",
  "/front_end/ui/RootView.js",
  "/front_end/ui/ListControl.js",
  "/front_end/ui/ReportView.js",
  "/front_end/ui/ListWidget.js",
  "/front_end/ui/SegmentedButton.js",
  "/front_end/ui/SettingsUI.js",
  "/front_end/ui/SoftContextMenu.js",
  "/front_end/ui/SoftDropDown.js",
  "/front_end/ui/TargetCrashedScreen.js",
  "/front_end/ui/SplitWidget.js",
  "/front_end/ui/ThrottledWidget.js",
  "/front_end/ui/Tooltip.js",
  "/front_end/ui/SearchableView.js",
  "/front_end/ui/SuggestBox.js",
  "/front_end/ui/TextPrompt.js",
  "/front_end/ui/ARIAUtils.js",
  "/front_end/ui/ZoomManager.js",
  "/front_end/ui/Toolbar.js",
  "/front_end/ui/TabbedPane.js",
  "/front_end/ui/Geometry.js",
  "/front_end/ui/ShortcutsScreen.js",
  "/front_end/ui/XLink.js",
  "/front_end/ui/XWidget.js",
  "/front_end/sdk/Connections.js",
  "/front_end/sdk/TargetManager.js",
  "/front_end/ui/UIUtils.js",
  "/front_end/sdk/Target.js",
  "/front_end/sdk/CookieModel.js",
  "/front_end/sdk/ContentProviders.js",
  "/front_end/sdk/CookieParser.js",
  "/front_end/sdk/ProfileTreeModel.js",
  "/front_end/sdk/ServerTiming.js",
  "/front_end/sdk/CSSMedia.js",
  "/front_end/sdk/CPUProfilerModel.js",
  "/front_end/sdk/CPUProfileDataModel.js",
  "/front_end/sdk/CSSMatchedStyles.js",
  "/front_end/sdk/CSSModel.js",
  "/front_end/sdk/CSSProperty.js",
  "/front_end/sdk/CSSStyleDeclaration.js",
  "/front_end/sdk/CSSRule.js",
  "/front_end/sdk/CSSStyleSheetHeader.js",
  "/front_end/sdk/ChildTargetManager.js",
  "/front_end/sdk/CSSMetadata.js",
  "/front_end/sdk/EmulationModel.js",
  "/front_end/sdk/DebuggerModel.js",
  "/front_end/sdk/DOMModel.js",
  "/front_end/sdk/HARLog.js",
  "/front_end/sdk/LayerTreeBase.js",
  "/front_end/sdk/DOMDebuggerModel.js",
  "/front_end/sdk/LogModel.js",
  "/front_end/sdk/TracingManager.js",
  "/front_end/sdk/TracingModel.js",
  "/front_end/sdk/IsolateManager.js",
  "/front_end/sdk/OverlayModel.js",
  "/front_end/sdk/ScreenCaptureModel.js",
  "/front_end/sdk/Script.js",
  "/front_end/sdk/ServiceWorkerCacheModel.js",
  "/front_end/sdk/RuntimeModel.js",
  "/front_end/sdk/ServiceWorkerManager.js",
  "/front_end/sdk/Resource.js",
  "/front_end/sdk/SecurityOriginManager.js",
  "/front_end/sdk/SourceMapManager.js",
  "/front_end/sdk/RemoteObject.js",
  "/front_end/sdk/SourceMap.js",
  "/front_end/sdk/NetworkLog.js",
  "/front_end/sdk/NetworkRequest.js",
  "/front_end/sdk/ResourceTreeModel.js",
  "/front_end/sdk/PaintProfiler.js",
  "/front_end/sdk/HeapProfilerModel.js",
  "/front_end/sdk/FilmStripModel.js",
  "/front_end/sdk/PerformanceMetricsModel.js",
  "/front_end/Images/treeoutlineTriangles.svg",
  "/front_end/sdk/NetworkManager.js",
  "/front_end/SupportedCSSProperties.js",
  "/front_end/sdk/ConsoleModel.js",
  "/front_end/mobile_throttling/throttlingSettingsTab.css",
  "/front_end/bindings/LiveLocation.js",
  "/front_end/console_counters/errorWarningCounter.css",
  "/front_end/product_registry/badge.css",
  "/front_end/product_registry/popup.css",
  "/front_end/bindings/CompilerScriptMapping.js",
  "/front_end/bindings/SASSSourceMapping.js",
  "/front_end/bindings/CSSWorkspaceBinding.js",
  "/front_end/bindings/ResourceScriptMapping.js",
  "/front_end/bindings/StylesSourceMapping.js",
  "/front_end/bindings/DefaultScriptMapping.js",
  "/front_end/bindings/ContentProviderBasedProject.js",
  "/front_end/bindings/BreakpointManager.js",
  "/front_end/bindings/FileUtils.js",
  "/front_end/bindings/ResourceMapping.js",
  "/front_end/bindings/DebuggerWorkspaceBinding.js",
  "/front_end/bindings/PresentationConsoleMessageHelper.js",
  "/front_end/bindings/TempFile.js",
  "/front_end/bindings/ResourceUtils.js",
  "/front_end/bindings/BlackboxManager.js",
  "/front_end/bindings/NetworkProject.js",
  "/front_end/browser_sdk/LogManager.js",
  "/front_end/mobile_throttling/ThrottlingPresets.js",
  "/front_end/mobile_throttling/MobileThrottlingSelector.js",
  "/front_end/mobile_throttling/NetworkThrottlingSelector.js",
  "/front_end/mobile_throttling/NetworkPanelIndicator.js",
  "/front_end/mobile_throttling/ThrottlingManager.js",
  "/front_end/console_counters/WarningErrorCounter.js",
  "/front_end/product_registry/BadgePool.js",
  "/front_end/mobile_throttling/ThrottlingSettingsTab.js",
  "/front_end/product_registry/ProductRegistry.js",
  "/front_end/components/imagePreview.css",
  "/front_end/components/jsUtils.css",
  "/front_end/components/ImagePreview.js",
  "/front_end/components/TargetDetachedDialog.js",
  "/front_end/components/JSPresentationUtils.js",
  "/front_end/components/Reload.js",
  "/front_end/components/DockController.js",
  "/front_end/components/Linkifier.js",
  "/front_end/emulation/devicesSettingsTab.css",
  "/front_end/emulation/geolocationsSettingsTab.css",
  "/front_end/emulation/deviceModeToolbar.css",
  "/front_end/persistence/editFileSystemView.css",
  "/front_end/persistence/workspaceSettingsTab.css",
  "/front_end/emulation/deviceModeView.css",
  "/front_end/emulation/inspectedPagePlaceholder.css",
  "/front_end/emulation/mediaQueryInspector.css",
  "/front_end/inspector_main/renderingOptions.css",
  "/front_end/emulation/sensors.css",
  "/front_end/inspector_main/nodeIcon.css",
  "/front_end/extensions/ExtensionView.js",
  "/front_end/persistence/PlatformFileSystem.js",
  "/front_end/extensions/ExtensionTraceProvider.js",
  "/front_end/extensions/ExtensionServer.js",
  "/front_end/extensions/ExtensionPanel.js",
  "/front_end/persistence/IsolatedFileSystem.js",
  "/front_end/persistence/IsolatedFileSystemManager.js",
  "/front_end/extensions/ExtensionAPI.js",
  "/front_end/persistence/Persistence.js",
  "/front_end/persistence/PersistenceUtils.js",
  "/front_end/persistence/PersistenceActions.js",
  "/front_end/persistence/EditFileSystemView.js",
  "/front_end/persistence/WorkspaceSettingsTab.js",
  "/front_end/emulation/AdvancedApp.js",
  "/front_end/persistence/FileSystemWorkspaceBinding.js",
  "/front_end/emulation/DevicesSettingsTab.js",
  "/front_end/emulation/InspectedPagePlaceholder.js",
  "/front_end/persistence/NetworkPersistenceManager.js",
  "/front_end/emulation/MediaQueryInspector.js",
  "/front_end/emulation/EmulatedDevices.js",
  "/front_end/emulation/DeviceModeModel.js",
  "/front_end/emulation/DeviceModeToolbar.js",
  "/front_end/emulation/DeviceModeView.js",
  "/front_end/emulation/DeviceModeWrapper.js",
  "/front_end/persistence/Automapping.js",
  "/front_end/emulation/GeolocationsSettingsTab.js",
  "/front_end/emulation/SensorsView.js",
  "/front_end/inspector_main/RenderingOptions.js",
  "/front_end/inspector_main/InspectorMain.js",
  "/front_end/main/SimpleApp.js",
  "/front_end/main/ExecutionContextSelector.js",
  "/front_end/main/Main.js",
  "/front_end/screencast/screencastView.css",
  "/front_end/screencast/ScreencastApp.js",
  "/front_end/screencast/InputModel.js",
  "/front_end/screencast/ScreencastView.js",
  "/front_end/data_grid/dataGrid.css",
  "/front_end/formatter/ScriptFormatter.js",
  "/front_end/Images/navigationControls_2x.png",
  "/front_end/help/releaseNote.css",
  "/front_end/formatter/FormatterWorkerPool.js",
  "/front_end/Images/largeIcons.svg",
  "/front_end/Images/smallIcons.svg",
  "/front_end/data_grid/ShowMoreDataGridNode.js",
  "/front_end/data_grid/SortableDataGrid.js",
  "/front_end/data_grid/ViewportDataGrid.js",
  "/front_end/help/ReleaseNoteView.js",
  "/front_end/help/Help.js",
  "/front_end/object_ui/objectPopover.css",
  "/front_end/object_ui/customPreviewComponent.css",
  "/front_end/help/ReleaseNoteText.js",
  "/front_end/object_ui/objectPropertiesSection.css",
  "/front_end/object_ui/objectValue.css",
  "/front_end/object_ui/JavaScriptREPL.js",
  "/front_end/data_grid/DataGrid.js",
  "/front_end/object_ui/ObjectPopoverHelper.js",
  "/front_end/object_ui/CustomPreviewComponent.js",
  "/front_end/object_ui/RemoteObjectPreviewFormatter.js",
  "/front_end/object_ui/JavaScriptAutocomplete.js",
  "/front_end/object_ui/ObjectPropertiesSection.js",
  "/front_end/console/consolePinPane.css",
  "/front_end/console/consoleContextSelector.css",
  "/front_end/console/consoleSidebar.css",
  "/front_end/console/consolePrompt.css",
  "/front_end/console/consoleView.css",
  "/front_end/console/ConsoleFilter.js",
  "/front_end/console/ConsolePinPane.js",
  "/front_end/console/ConsoleContextSelector.js",
  "/front_end/console/ConsoleViewport.js",
  "/front_end/console/ConsoleSidebar.js",
  "/front_end/console/ConsoleViewMessage.js",
  "/front_end/console/ConsoleView.js",
  "/front_end/console/ConsolePanel.js",
  "/front_end/console/ConsolePrompt.js",
  "/front_end/cm/codemirror.css",
  "/front_end/cm/multiplex.js",
  "/front_end/cm/markselection.js",
  "/front_end/cm/comment.js",
  "/front_end/cm/closebrackets.js",
  "/front_end/cm/matchbrackets.js",
  "/front_end/cm/overlay.js",
  "/front_end/cm/foldcode.js",
  "/front_end/cm/activeline.js",
  "/front_end/cm/foldgutter.js",
  "/front_end/cm/brace-fold.js",
  "/front_end/cm/codemirror.js",
  "/front_end/text_editor/autocompleteTooltip.css",
  "/front_end/text_editor/cmdevtools.css",
  "/front_end/text_editor/CodeMirrorUtils.js",
  "/front_end/cm_web_modes/htmlembedded.js",
  "/front_end/cm_web_modes/htmlmixed.js",
  "/front_end/cm_web_modes/xml.js",
  "/front_end/cm_web_modes/javascript.js",
  "/front_end/cm_web_modes/css.js",
  "/front_end/text_editor/TextEditorAutocompleteController.js",
  "/front_end/text_editor/CodeMirrorTextEditor.js"
];

function addCache({ url, content, contentType }) {
  caches.open(storageName)
    .then(cache => {
      const response = new Response(content, {
        headers: { 'Content-Type': contentType || 'text/plain' }
      });

      const request = new Request(url);

      cache.put(request, response).then(() => {
        console.log(url, 'covered');
      });
    })
}

// Example: addCache({ url: '/dist/test.js', content: 'test' })

self.addEventListener('install', event => {
  self.skipWaiting();
  // event.waitUntil(
    caches.open(storageName)
      .then(cache => {
        preload.forEach(it => cache.add(it));
        // return cache.addAll(preCacheTargets);
      })
  // );
});

self.addEventListener('activate', event => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('message', event => {
  const { action, url, content, contentType } = event.data || {};
  if (action === 'cdp_override_add') {
    addCache({ url, content, contentType });
  }
})

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => {
        if (response) {
          return response;
        }

        const url = new URL(event.request.url);
        if (!url.pathname.includes('/front_end/') || url.pathname.includes(".html")) {
          return fetch(event.request);
        }

        return fetch(event.request).then(
          response => {
            if (!response || response.status !== 200 || response.type !== 'basic') {
              return response;
            }
            const responseToCache = response.clone();
            caches.open(storageName)
              .then(cache => {
                cache.put(event.request, responseToCache);
              });
            return response;
          }
        );
      })
  );
});
